name: DailyJudge

on: 
  workflow_dispatch:  # Workflow中的运行按钮
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 4-14 * * *" # 早上十二点到晚上十点每小时一次
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 star 来运行脚本
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装轮子
      run: |
        pip install -r requirements.txt
    - name: Run script
      env:
        csrf: ${{ secrets.csrf }}
        sessdata: ${{ secrets.sessdata }}
        giveup: ${{ secrets.GiveUp }}
        delay: ${{ secrets.delay }}
        JudgeProportion: ${{ secrets.JudgeProportion }}
      run: |
        python3 Main.py "$csrf" "$sessdata" "$giveup" "$delay" "$JudgeProportion"
